### ISSUE TITLE
기능 완성 후 css 스타일 입히기

### ISSUE THREAD

**Issue by thinkanddoit** [thinkanddoit/vanilla-js-spa#6]
### 1. 어떤 요구사항을 개발 할 것인가
- 기능 완성 후 css 스타일 입히기

### 2. 구체적으로 명세
- css 방식 선정
- 적용 및 화면별 스타일 입히기

### 3. Todo List
- [ ] css 방식 선정
- [ ] 관련 라이브러리 설치 및 베이스 준비
- [ ] 홈화면 적용
- [ ] upload 화면 적용
- [ ] post 화면 적용
